Feature/140 throw user out of session
Sybit-Education/Diveni pull request #156
Opened 2022-04-20 12:49 UTC by KzuDemEvin

#140 
- The host has the ability to throw a user out of session
- Add a wrapper component for components which handles throwing out users
- The wrapper supports lazy loading of the child components

**Images showing the changes in the application:**
![KickMember1](https://user-images.githubusercontent.com/65013155/164233314-544e0184-2f47-4f2a-b9d4-6af8835d2411.gif)
![KickMember2](https://user-images.githubusercontent.com/65013155/164233299-57fc5737-3096-47fc-b3ef-d92412151729.gif)
![KickMember3](https://user-images.githubusercontent.com/65013155/164233307-f4fbadd3-8290-48ba-a63a-345b97bf1fdf.gif)

2022-04-26 18:56 UTC, stritti commented
@Saskia0905 could you add some of the images to docs, too please?

2022-04-26 19:02 UTC, stritti requested changes

2022-04-26 19:02 UTC, stritti commented on frontend/src/views/SessionPage.vue
> +        <KickUserWrapper
use kebap-style

2022-04-27 11:05 UTC, Saskia0905 commented
> @Saskia0905 could you add some of the images to docs, too please?

@stritti I've done this just at the moment.

2022-05-04 13:21 UTC, stritti approved these changes

2022-05-19 08:16 UTC, merged