#257 add an auto reveal checkbox, for the session admin
Sybit-Education/Diveni pull request #269
Opened 2023-02-16 17:17 UTC by SponsoredByPuma

Gave the admin the option to automatic reveal the votes, once everybody voted or to wait for the timer to come to an end. While the Estimations are still running, you cannot change the mode.

2023-02-22 09:06 UTC, stritti commented
Could you also update user docs for this feature?

2023-02-22 12:40 UTC, stritti approved these changes

2023-03-07 07:59 UTC, stritti requested changes

2023-03-07 07:59 UTC, stritti commented on backend/src/main/java/io/diveni/backend/controller/WebsocketController.java
> +  @MessageMapping("/vote/autoreveal")
The endpoints are confusing:
here: `/vote/autoreveal`
in line 153 `/startVoting/autoreveal`

Do not use captial letters in uri. Probably we could make more descriptive endpoints?

2023-05-02 15:25 UTC, KzuDemEvin commented
Why is this not supported for planning without user stories?

2023-05-08 09:06 UTC, SponsoredByPuma commented
HI @KzuDemEvin,
It should also work for NO_US mode now. I also removed some unnecessary functions.

2023-05-16 14:03 UTC, KzuDemEvin submitted a review, later dismissed

2023-10-19 07:19 UTC, stritti commented
Merge Conflicts should be fixed

2023-10-25 09:55 UTC, stritti requested changes

2023-10-25 09:55 UTC, stritti commented on frontend/src/locales/de.json
translations should be done within Crowdin. See translation guide: https://sybit-education.github.io/Diveni/guide/translations

2023-11-03 10:13 UTC, merged