Feature/209 configuration setup
Sybit-Education/Diveni pull request #272
Opened 2023-03-06 15:56 UTC by KzuDemEvin

# Issue #209 
* Move environment variables from frontend to backend
* Add REST-Controller to recieve config required for the frontend
* Disable jira services if not all required parameters are set
* Update/Fix docs

2023-03-07 07:35 UTC, stritti requested changes
Please add error message also to exception to expose to client too.
Could we add a link to docs in the exception text to give a hint how to solve the issue?

2023-03-07 07:35 UTC, stritti commented on backend/src/main/java/io/diveni/backend/controller/ProjectManagementController.java
> +      throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Please add also the error message to the exception.

2023-03-07 07:35 UTC, stritti commented on backend/src/main/java/io/diveni/backend/controller/ProjectManagementController.java
> +      throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Please add also the error message to the exception.

2023-03-07 07:35 UTC, stritti commented on backend/src/main/java/io/diveni/backend/controller/ProjectManagementController.java
> +      throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Please add also the error message to the exception.

2023-03-07 07:35 UTC, stritti commented on backend/src/main/java/io/diveni/backend/controller/ProjectManagementController.java
> +      throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Please add also the error message to the exception.

2023-03-07 07:35 UTC, stritti commented on backend/src/main/java/io/diveni/backend/controller/ProjectManagementController.java
> +      throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Please add also the error message to the exception.

2023-03-07 07:35 UTC, stritti commented on backend/src/main/java/io/diveni/backend/controller/ProjectManagementController.java
> +      throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Please add also the error message to the exception.

2023-03-07 07:35 UTC, stritti commented on backend/src/main/java/io/diveni/backend/controller/ProjectManagementController.java
> +      throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Please add also the error message to the exception.

2023-03-07 13:09 UTC, KzuDemEvin commented
> Could we add a link to docs in the exception text to give a hint how to solve the issue?

I think this would be problematic in the case the documentation changes. You have to keep track of all the references.
A workaround would be to work with error codes.

2023-03-07 13:15 UTC, KzuDemEvin commented
# Visualized changes in the docs: (including collapsible at the bottom)
![image](https://user-images.githubusercontent.com/65013155/223432116-2c764767-7eea-4684-a0ac-21233b08fc45.png)

## 1. unfolded:
![image](https://user-images.githubusercontent.com/65013155/223432622-13686e82-bf09-4c24-90ad-ba4115460965.png)

## 2. unfolded:
![image](https://user-images.githubusercontent.com/65013155/223432777-203b5484-1da7-4f0b-b87b-3396d067f4ef.png)

2023-05-31 11:12 UTC, SponsoredByPuma approved these changes

2023-06-20 08:46 UTC, merged