#284 Console error when creating a new session with user stories
Sybit-Education/Diveni pull request #286
Opened 2023-04-28 08:40 UTC by SponsoredByPuma

Removed the invoke function call. Looks like everything works just as usual even without it.

2023-04-28 17:01 UTC, stritti reviewed
Could we then not remove complete onMounted hook?

2023-05-02 09:06 UTC, KzuDemEvin requested changes

2023-05-02 09:06 UTC, KzuDemEvin commented on frontend/src/components/MarkdownEditor.vue
> +      this.getEditorRef();
Can be removed

2023-05-02 09:13 UTC, KzuDemEvin commented
I think that the `change()` method can also be removed because it does not get invoked in the parent component.

2023-05-08 08:31 UTC, KzuDemEvin approved these changes

2023-06-02 08:18 UTC, merged