#306 Member does not see the description of the Userstory
Sybit-Education/Diveni pull request #308
Opened 2023-06-09 13:28 UTC by SponsoredByPuma

2023-06-27 09:26 UTC, KzuDemEvin requested changes
- Is the position really needed as a property? Or can it be replaced by the id of the user stories or the index in the loop?
- I had a suggestion regarding the update policy for user stories.

2023-06-27 09:26 UTC, KzuDemEvin commented on frontend/src/components/MobileStoryList.vue
> +      :key="story.position"
Why don't you use the property `id` of userStories or use the `index` as key?

2023-06-27 09:26 UTC, KzuDemEvin commented on frontend/src/components/MobileStoryTitle.vue
> +        :key="story.position"
Why don't you use the property `id` of userStories or use the index `idx` as key?

2023-06-27 09:26 UTC, KzuDemEvin commented on frontend/src/components/UserStoryDescriptions.vue
> +        :key="story.position"
Why don't you use the property `id` of userStories or use the index `idx` as key?

2023-06-27 09:26 UTC, KzuDemEvin commented on frontend/src/components/UserStoryDescriptions.vue
> +    },
Perhaps you can already call `this.publishChanges(index);` here, so there is no need to press the button to update the user story for all members.

2023-07-07 13:31 UTC, SponsoredByPuma commented
Thanks for the advice @KzuDemEvin. I removed the position attribute and added id as the key. Also I extended the mobile classes for the id attribute since it was missing in those. Last but not least the description now updates as soon as you click next to the markdown editor box.

2023-07-10 08:42 UTC, KzuDemEvin approved these changes

2023-07-13 09:22 UTC, merged