update spanish and italian translate 11072023
Sybit-Education/Diveni pull request #354
Opened 2023-07-11 11:25 UTC by johnfelipe

2023-07-14 09:48 UTC, KzuDemEvin requested changes
Thank you for your improvements!
For a more consistent translation, both the `Backend` and the `Frontend` should be capitalized.

2023-07-14 09:48 UTC, KzuDemEvin commented on frontend/src/locales/it.json
> +      "backend": "Licenze (backend)",
Use `Backend` and `Frontend` instead of `backend` and `frontend`

2023-07-14 10:22 UTC, johnfelipe commented
Changed today

El vie, 14 jul 2023, 4:48 a. m., Kevin Schoch ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
>
> Thank you for your improvements!
> For a more consistent translation, both the Backend and the Frontend
> should be capitalized.
> ------------------------------
>
> In frontend/src/locales/it.json
> <https://github.com/Sybit-Education/Diveni/pull/354#discussion_r1263530735>
> :
>
> >        "repository": "GitHub",
>        "docs": "Documentazione"
>      },
>      "licenses": {
> -      "frontend": "Licenze (Frontend)",
> -      "backend": "Licenze (Backend)",
> +      "frontend": "Licenze (frontend)",
> +      "backend": "Licenze (backend)",
>
> Use Backend and Frontend instead of backend and frontend
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Sybit-Education/Diveni/pull/354#pullrequestreview-1529983506>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADIWFACVY5BCNHTJRGDY6DXQEIXLANCNFSM6AAAAAA2F3NH4Q>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-08-04 08:58 UTC, KzuDemEvin commented
Can you push the changes?

2023-08-14 10:30 UTC, KzuDemEvin approved these changes

2023-08-17 07:43 UTC, SponsoredByPuma approved these changes

2023-08-17 08:09 UTC, merged