#364 Dark Mode
Sybit-Education/Diveni pull request #366
Opened 2023-07-24 07:58 UTC by SponsoredByPuma

implemented a Dark Mode for Diveni

2023-07-24 12:36 UTC, SponsoredByPuma commented
Everything should be styleable right now. Now we just need to find the correct colours for the elements.

2023-09-28 09:45 UTC, stritti requested changes
Please avoid styles and use class definitions instead.

There are also some lint-issues.

2023-09-28 09:45 UTC, stritti commented on frontend/src/components/navigation/TopNavigationBar.vue
> +      <input
I would suggest to externalize toggler to own component.

2023-09-28 09:45 UTC, stritti commented on frontend/src/components/CardSetComponent.vue
> +            :class="[selectedCardSet.name === item.name ? 'selectedCard' : 'inActiveCard',
create a method and reduce redundancy

2023-09-28 09:45 UTC, stritti commented on frontend/src/components/actions/SessionCloseButton.vue
> +      <p v-if="userStoryMode !== 'NO_US'" style="color:black;">
use class definition instead of styles

2023-09-28 09:45 UTC, stritti commented on frontend/src/components/actions/SessionCloseButton.vue
> +      <p class="my-4" style="color:black;">
use class definition instead of styles

2023-09-28 09:45 UTC, stritti commented on frontend/src/components/navigation/TopNavigationBar.vue
> +      userTheme: "light-Theme"
`Theme` or `theme`? I would suggest to use const

2023-09-28 09:45 UTC, stritti commented on frontend/src/views/AboutPage.vue
> +      <a href="https://github.com/Sybit-Education/Diveni/blob/main/LICENSE" target="_blank" style="color: var(--linkColor);"
use class definition instead of styles

2023-09-28 09:45 UTC, stritti commented on frontend/src/views/AboutPage.vue
> +    <h2 style="color: var(--text-primary-color);">Open Source & Contribution</h2>
use class definition instead of styles

2023-09-28 09:45 UTC, stritti commented on frontend/src/views/AboutPage.vue
> +      <a href="https://github.com/Sybit-Education/Diveni" target="_blank" style="color: var(--linkColor);">GitHub</a>:
use class definition instead of styles

2023-09-28 09:45 UTC, stritti commented on frontend/src/views/AboutPage.vue
> +      <li><a href="https://github.com/Sybit-Education/Diveni/" target="_blank" style="color: var(--linkColor);">Code</a></li>
use class definition instead of styles

2023-09-28 09:45 UTC, stritti commented on frontend/src/views/AboutPage.vue
> +      <li><a href="https://github.com/Sybit-Education/Diveni/issues" target="_blank" style="color: var(--linkColor);">Issues</a></li>
use class definition instead of styles

2023-09-28 09:45 UTC, stritti commented on frontend/src/views/AboutPage.vue
> +        <a href="https://github.com/Sybit-Education/Diveni/discussions" target="_blank" style="color: var(--linkColor);"
use class definition instead of styles

2023-09-28 09:45 UTC, stritti commented on frontend/src/views/AboutPage.vue
> +    <h2 style="color: var(--text-primary-color);">Credits</h2>
use class definition instead of styles

2023-10-06 18:56 UTC, stritti commented
I think this could be merged. Probably upcoming changes could be done in separate issues.

2023-10-12 08:13 UTC, Dan1elBox commented
It looks really good👍 
The only issue I've noticed is the incorrect scrollbar coloring for story titles in Firefox, as shown in the picture, but you're already aware of that:
![Coloring Scrollbar](https://github.com/Sybit-Education/Diveni/assets/142214610/b0abe96a-c724-4305-89da-6a2e8d19f5ca)

<br>
Also is it intentional that on the session page, the list of issues, as well as the title and description, are all arranged one below the other?

Old session page alignment:
![Old-Session](https://github.com/Sybit-Education/Diveni/assets/142214610/cc955dd9-6cf3-4f74-99fb-0c9a5abca011)

New session page alignment:
![New-Session](https://github.com/Sybit-Education/Diveni/assets/142214610/e060f56e-00f7-42c7-9b8f-292d7b231381)

2023-10-19 07:56 UTC, stritti approved these changes

2023-10-19 08:30 UTC, merged